apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Declare our root directory where to find our charts
helmGlobals:
  chartHome: "../../../../manifests"
# We declare the name of our specific chart 
helmCharts:
  - name: custom-webapp
    # Declare and set the values we want to override
    valuesInLine:
      name: app1
      image:
        repository: nginx
        image: nginx
        tag: '1.2.3'
        port: 80     
