apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/deployment.yaml
- ../../../base/service.yaml

patches:
- target:
    kind: Deployment
    name: frontend-deployment
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: nginx:latest
- target:
    kind: Service
    name: frontend-service
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 80
