apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- sealed-secrets-key.yaml

helmGlobals:
  chartHome: '../../../../../manifests'

helmCharts:
  - name: 'sealed-secrets'
    releaseName: sealed-secrets
    namespace: kube-system
    includeCRDs: true
