apiVersion: v1
items:
- apiVersion: v1
  data:
    tls.crt: 
    tls.key: 
  kind: Secret
  metadata:
    labels:
      sealedsecrets.bitnami.com/sealed-secrets-key: active
    name: sealed-secrets-keyjqt9f
    namespace: sealed-secrets
  type: kubernetes.io/tls
kind: List
metadata:
  resourceVersion: ""
