apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
      - name:  {{ .Values.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.image }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.image.port }}
        {{- if or .Values.configmap.enabled .Values.secrets.enabled }}
        envFrom:        
        {{- if .Values.configmap.enabled }}
        - configMapRef:
            name: {{ .Values.name }}
        {{- end }}
        {{- if .Values.secrets.enabled }}
        - secretRef:
            name: {{ .Values.name }}-secret
        {{- end }}
        {{- end }} 
