apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../root-tenant

patches:
# $patch: delete and $patch: replace also work in the inline patch. 
# here, Change the previous applied inline patch to delete the container nginx
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend-deployment
    spec:
      template:
        spec:
          containers:
          - name: app
            $patch: delete